# Generated by Django 2.1.3 on 2018-11-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0002_auto_20181104_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='color',
            field=models.CharField(default='#236aff', max_length=10),
        ),
    ]
