# Generated by Django 2.1.3 on 2018-11-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0003_activity_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.CharField(choices=[('월', '월요일'), ('화', '화요일'), ('수', '수요일'), ('목', '목요일'), ('금', '금요일'), ('토', '토요일'), ('일', '일요일')], default='월', max_length=3),
        ),
    ]
