# Generated by Django 2.1.3 on 2018-11-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0004_auto_20181115_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.CharField(choices=[('월요일', '월요일'), ('화요일', '화요일'), ('수요일', '수요일'), ('목요일', '목요일'), ('금요일', '금요일'), ('토요일', '토요일'), ('일요일', '일요일')], default='월요일', max_length=3),
        ),
    ]
