# Generated by Django 2.1.3 on 2018-11-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0005_auto_20181115_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
